import fs from "fs";
import path from "path";
import { traceLogger } from "./trace-logger";

export interface DocWorkerReport {
  timestamp: string;
  architecture_updated: boolean;
  mermaid_updated: boolean;
  nodes_analyzed: string[];
  recent_traces_count: number;
}

export class DocWorker {
  private docsDir: string;
  private archDocPath: string;
  private mermaidDocPath: string;

  constructor() {
    this.docsDir = path.resolve(process.cwd(), "docs");
    this.archDocPath = path.join(this.docsDir, "system_architecture.md");
    this.mermaidDocPath = path.join(this.docsDir, "state_graph.mermaid");
    this.ensureDocsDir();
  }

  private ensureDocsDir(): void {
    try {
      if (!fs.existsSync(this.docsDir)) {
        fs.mkdirSync(this.docsDir, { recursive: true });
      }
    } catch {
      // ignore
    }
  }

  /**
   * Generates the mermaid state graph definition reflecting current state nodes and flow
   */
  public generateMermaidGraph(): string {
    return `stateDiagram-v2
    [*] --> UnifiedTopicNode: Single Source of Truth (3 Pillars: What / Why / Presentation)

    state "The Mind-State Memory Architecture" as MindStateCore {
        UnifiedTopicNode --> ContextAgent: Inject Empath Framing, Sensitivities & Calibrated Depth
        UnifiedTopicNode --> DiscoveryAgent: Curate High-Signal Wire Queries & Strict Quality Filter
        ContextAgent --> InteractiveDialogue: Calibrated Empath Dialogue Turns & Inverted Flow
        InteractiveDialogue --> ObserverAgent: Active Listener (Sentiment, Reactions & Nuance)
        ObserverAgent --> TopicMutationEngine: Pure Agentic Tool Calling (create_topic / update_topic)
        TopicMutationEngine --> UnifiedTopicNode: Cumulative Living Topic Dossier Evolution
        ObserverAgent --> InterestHarmonizer: Background Graph Saturation Reconciliation (>= 25 Topics)
        InterestHarmonizer --> UnifiedTopicNode: Harmonized Topic Nodes
    }

    state "Node A: Epistemology Agent" as NodeA {
        DiscoveryAgent --> BiasStripper: Multi-source Articles
        BiasStripper --> DeltaExtractor: Strip Emotive Rhetoric
        DeltaExtractor --> PureFactObject: Verified Entities + Agreed Facts + Disputed Claims
    }

    state "Node B: Telemetry & Graph Agent" as NodeB {
        UserTelemetry --> BehavioralGraph: Dwell Time / Scroll Depth / Bounce
        BehavioralGraph --> ObserverAgent: Feed Interaction Telemetry
    }

    state "Node C: Serendipity Agent" as NodeC {
        MultiArmedBandit --> Exploitation: 80% High-weight Nodes
        MultiArmedBandit --> Exploration: 20% Adjacent/Unrelated Topics
        Exploration --> AnchorResolution: Concept Anchoring Bridge
    }

    state "Node D: Synthesis Agent" as NodeD {
        FormatDecider --> BulletedList: Low Cognitive Load
        FormatDecider --> GenerativeUIWidget: Data Heavy Facts
        FormatDecider --> StructuredNarrative: Deep Dive
        GenerativeUIWidget --> NextJSRenderer: Deliver to Presentation Layer
    }

    NodeA --> NodeC: Evaluate Candidate Facts
    NodeC --> NodeD: Route Payload with Anchors
    NodeD --> [*]: Live UI / Generative Stream
`;
  }

  /**
   * Generates full living system architecture markdown documentation
   */
  public generateArchitectureDoc(): string {
    const recentTraces = traceLogger.getRecentTraces(20);
    const traceSummary = recentTraces.length > 0
      ? recentTraces
          .map(
            (t) =>
              `- **[${t.timestamp.slice(11, 19)}] \`${t.node_name}\`**: ${t.reasoning_rationale} *(latency: ${t.latency_ms}ms)*`
          )
          .join("\n")
      : "_No pipeline traces recorded in current run yet._";

    return `# Project Aletheia: Living System Architecture & Mind-State Memory

> **Auto-Generated by DocWorker Agent**
> **Last Synchronized:** ${new Date().toISOString()}

---

## 1. System Philosophy & Mind-State Continuity
**Project Aletheia: The Mind-State Memory Architecture** transforms stateless news tools into a continuous, stateful, and empathy-driven intelligence platform:
1. **Deep Continuity**: Maintains long-term psychological understanding across interactions, tracking *why* users care and their technical depth across domains.
2. **Psychological Awareness**: Injects emotional trajectory, sensitivities, and boundaries into prompts to ensure respectful, nuanced interaction without formulaic conversational repetition.
3. **Intentional Discovery**: Translates deep user preferences into multi-tiered search queries and rigorous quality/anti-preference filters, rejecting low-signal clickbait before ingestion.
4. **Epistemic Deliberation**: Enforces a strict prefix-rationale architecture where agent cognition and fact-checking precede generation, grounded in real-time temporal and spatial realities.
5. **Observability-Driven Adaptation**: Continuously evolves living topic dossiers in the background via the Observer Agent with transparent trace logging.

---

## 2. Dynamic State Graph Topology

\`\`\`mermaid
${this.generateMermaidGraph()}
\`\`\`

---

## 3. Living Topic Dossiers: The 3 Core Pillars & Cumulative Evolution

Aletheia models user knowledge not as isolated keywords or flat scores, but as rich, cumulative **Living Topic Dossiers** within the \`UnifiedTopicNode\`:

### The 3 Core Pillars
1. **What They Care About (\`what_they_care_about\`)**:
   - The cumulative scope of specific sub-domains, technologies, architectures, and empirical focus areas the user follows.
   - Distinct from general curiosity; captures exact operational boundaries.
2. **Why They Care (\`why_they_care\`)**:
   - The user's underlying intellectual stakes, motivations, philosophical worldview, and core concerns.
   - Deepens continuously across conversation turns without dropping prior context.
3. **How Best to Present Stories (\`presentation_strategy\`)**:
   - Editorial direction derived strictly from how the user responds to content, engages with topics, and expresses likes or critiques.
   - Avoids generic templates in favor of tailored density and analytical framing.

### Cumulative Synthesis & Non-Overwrite Guarantee
- **Living Narrative (\`living_narrative\`)**: A multi-dimensional narrative synthesizing historical context with the newest discussion.
- **Evolution Insight (\`evolution_insight\`)**: A discrete, single-sentence note capturing the exact incremental shift or nuance introduced in each interaction.
- **Evolution Timeline (\`evolution_timeline\`)**: An append-only audit trail preserving timestamped insights, trigger sources, and verbatim user evidence.
- **Preferences & Anti-Preferences**: Granular tracking of \`likes_and_angles\` vs \`dislikes_and_critiques\`.

---

## 4. Epistemic Deliberation & Inverted Execution Ordering

The conversational intake pipeline in \`DialogueAgent\` operates under an **inverted execution order** designed to prevent hallucination and enforce factual grounding:

\`\`\`text
1. Semantic Topic Resolver & Feed Filter FIRST
   └── Traverses user knowledge graph, identifies active discussion subject,
       and immediately filters candidate feed stories by semantic affinity.

2. Context Agent (The Empath) Grounding SECOND
   └── Constructs context envelope with calibrated technical depth,
       active sensitivities/boundaries, and scores candidate feed stories.

3. Epistemic Sufficiency & Temporal Evaluation THIRD
   └── DeepSeek evaluates whether local feed context contains verified facts
       for the current calendar year. If insufficient or outdated,
       autonomously executes "search_internet" via FreeNewsFetcher.

4. Prefix-Rationale Dual-Intent Synthesis LAST
   └── Deliberates first: outputs agent_internal_rationale before message text.
       Streams response tokens using JsonMessageStreamExtractor.
\`\`\`

### Architectural Rules & Guardrails
- **Prefix-Rationale Decision Ordering**: The LLM must construct its internal cognitive rationale (*emotional state, curiosity focus, pedagogical strategy, why this response*) before emitting the conversational message.
- **Real-Time Temporal & Spatial Grounding**: Prompts inject real-world date/time, client timezone, user region, and article publication age to prevent chronological confusion.
- **Absolute Ban on Regex Heuristics**: Epistemic routing and tool selection rely entirely on LLM-driven structured tool-calling protocols.
- **Zero Test-Case Overfitting**: Universal domain-agnostic ontologies and prompts prevent hardcoded test heuristics.

---

## 5. Discrete Topic Mutation & Graph Harmonization

### Topic Mutation Engine (\`TopicMutationEngine\`)
The Observer Agent mutates topics exclusively through atomic, discrete tool calls:
- \`create_topic\`: Establishes a new topic dossier with validated user evidence.
- \`update_topic\`: Integrates new nuances, updates weights, and appends to the evolution timeline without overwriting prior history.

### Interest Harmonizer (\`InterestHarmonizer\`)
When the topic graph approaches saturation ($\ge 25$ topics) or when triggered via \`/api/interests/harmonize\`:
- Evaluates semantic overlap across topic dossiers.
- Merges redundant sub-themes, promotes cross-domain intersections, and purges stale nodes.
- Records all actions in the audited \`harmonization_runs\` journal on the \`UnifiedTopicNode\`.

---

## 6. Feed Personalization, Deduplication & Narrative Citations

- **Semantic Matcher**: Computes concept sphere intersections, accounting for knowledge graph weights, curiosity vectors, and domain ontologies.
- **Topic Briefs Builder**: Aggregates stories into intelligence dossiers with velocity indicators (*breaking, active, recent, steady, dormant*).
- **Syndication Deduplication**: Groups identical syndicated wire coverage across news agencies to maintain feed diversity.
- **Sentence-Level Narrative Citations**: Generates synthesized narrative summaries where each sentence features interactive, clickable source citations linked to the \`SourceReaderModal\`.
- **Decoupled Telemetry**: Passive dwell and scroll tracking is decoupled from feed rendering to eliminate reshuffling and UI jitter.

---

## 7. PostgreSQL Persistence & Seed Architecture

- **PostgreSQL 16 + pgvector**: Secure persistence with tables for \`unified_topic_nodes\`, \`user_knowledge_graphs\`, \`pure_fact_objects\`, \`behavioral_telemetry\`, \`agent_trace_logs\`, and \`chat_sessions\`.
- **JSONB DDL Support**: Schema includes \`recent_topic_diffs\` and \`harmonization_runs\` on \`unified_topic_nodes\`.
- **Canonical Seed State (\`SEED_DATA_STATE\`)**: Embedded baseline data ensures consistent, resilient bootstrapping across local Docker and production AWS environments.
- **Idempotent Migrations (\`npm run db:migrate\`)**: Safely applies schema updates with \`ALTER TABLE ... ADD COLUMN IF NOT EXISTS\`.

---

## 8. Reverse Proxy & Production Infrastructure

- **AWS ECS Fargate**: Containerized Next.js standalone server deployed in \`us-east-1\`.
- **AWS RDS PostgreSQL**: Dedicated \`db.t4g.micro\` PostgreSQL instance with SSL enforcement.
- **Route 53 & CloudFront**: Edge CDN routing \`news.ciclops.io\` with shared wildcard cookie authentication (\`ciclops.io\`).
- **Production Inspector (\`npm run prod:inspect\`)**: Interactive CLI tool for inspecting live production telemetry, user topics, and database connectivity.
- **Local Development**: Supports local development with Docker Compose (\`docker-compose.dev.yml\`) and automated Caddy reverse proxy.

---

## 9. Micro-Agent Node Contracts & Execution Registry

- **Context Agent (\`node_context\`)**: Injects empath framing, active sensitivities, boundaries, and calibrated technical depth into conversational prompts.
- **Discovery Agent (\`node_discovery\`)**: Curates wire queries, applies anti-preference filters, and rejects sensationalist clickbait.
- **Observer Agent (\`node_observer\`)**: Actively evaluates user dialogue and telemetry to emit atomic topic mutation tool calls.
- **Epistemology Agent (\`node_a_epistemology\`)**: Strips emotive rhetoric and produces verifiable \`PureFactObject\` records with agreed facts and disputed claims.
- **Telemetry Agent (\`node_b_telemetry\`)**: Tracks passive user dwell and scroll depth to adjust interest weights.
- **Serendipity Agent (\`node_c_serendipity\`)**: Balances exploitation (80%) and exploration (20%) via an $\\\\epsilon$-greedy multi-armed bandit.
- **Synthesis Agent (\`node_d_synthesis\`)**: Formats pure facts into digestible event cards, briefings, and generative UI widgets.

---

## 10. Active Observability Audit Trail (Latest Node Traces)

${traceSummary}
`;
  }

  /**
   * Sync documentation files
   */
  public syncDocs(): DocWorkerReport {
    this.ensureDocsDir();
    const mermaidContent = this.generateMermaidGraph();
    const archContent = this.generateArchitectureDoc();

    fs.writeFileSync(this.mermaidDocPath, mermaidContent, "utf-8");
    fs.writeFileSync(this.archDocPath, archContent, "utf-8");

    const traces = traceLogger.getRecentTraces();

    return {
      timestamp: new Date().toISOString(),
      architecture_updated: true,
      mermaid_updated: true,
      nodes_analyzed: [
        "node_context",
        "node_discovery",
        "node_observer",
        "node_a_epistemology",
        "node_b_telemetry",
        "node_c_serendipity",
        "node_d_synthesis",
      ],
      recent_traces_count: traces.length,
    };
  }
}

export const docWorker = new DocWorker();

